apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cloud
  name: rocky-deployment
  labels:
    app: roc-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: roc-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: roc-app
    spec:
      imagePullSecrets:
        - name: dockerhub-credentials
      containers:
        - name: rocky-container
          image: shadowhub/blog:latest
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: 600m
              memory: 10Gi
            requests:
              cpu: 200m
              memory: 228Mi
          # livenessProbe:
          #   httpGet:
          #     path: /healthz
          #     port: 3000
          #   periodSeconds: 20
          #   failureThreshold: 3
          # readinessProbe:
          #   httpGet:
          #     path: /readyz
          #     port: 3000
          #   periodSeconds: 20
          #   failureThreshold: 3