apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rocky-application-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/chizchig/rocky.git
    targetRevision: HEAD
    path: environment/prod
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cloudy-prod-namespace
  syncPolicy:
    automated:
      selfHeal: true
      prune: true